version: '3'

services:
  web:
        build: .
        environment:
            - NODE_ENV=development
        command: "npm start"
        volumes:
            - .:/usr/app/
            - /usr/app/node_modules
        ports:
            - "8080:8080"
        links:
            - mongodb
        depends_on:
            - mongodb
  mongodb:
        image: mongo:3.4.5
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
          - MONGODB_USER="user" 
          - MONGODB_PASS="pass"
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet
