version: '3'

services:
  nginx:
    build: ./react-app
    ports:
        - "80:80"
  node:
        build: ./node
        environment:
            - MONGO_URL=mongodb://mongo:27017/
            - OPEN_URL=https://itunes.apple.com/search?term=eminem&country=ro
            - DATABASE_NAME=dataGeneratorDb
            - COLLECTION_NAME=tracks
        command: "npm start"
        volumes:
            - ./node:/usr/app/
        ports:
            - 8083:8080
        links:
            - mongo
        depends_on:
            - mongo
  mongo:
        image: mongo:3.4.5
        container_name: "mongo"
        environment:
          - AUTH=no
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
          - MONGODB_USER="user" 
          - MONGODB_PASS="pass"
        volumes:
          - data:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles
volumes:
  data: